export default function ProjectData(){
    return (
        [
            {
                ProjectTitle: "Tenzies Game",
                Description1: "A simple Tenzies game built with React and JavaScript. Players roll dice until all dice show the same number, with the ability to hold dice to keep their values between rolls",
                Description2: "Users are given 10 dice and can hold any dice so that it isnt rerolled once the rerolled button is clicked, the held dice can be any number and doesnt have to be same number, however if all the held numbers are not the same the player cannot win.",
                Description3: "Holding a dice will make it green, making it clearly visible that its being held and clicking it again makes it go back to normal. The whole interface is made to be accessible so th egame can be played with only keyboard too, just with tab and enter to select the dices and reroll.",
                Description4: "Once the game has been won confetti will fall from the top of the screen and the user will be given the opportunity to play again. The whole game is very simple but is made to be fun and cross-platform. Designed to fit any user's screen.",
                Description5: "",
                Img1: '/Projects/Images/Tenzies.png',
                Img2: '/Projects/Images/Tenzies2.png',
                Img3: '/Projects/Images/Tenzies4.png',
                Img4: '',
                TechUsed: ['JavaScript', 'React', 'HTML5', 'CSS3'],
                Link: 'https://github.com/AashiqDina/Tenzies',
                TryableLink: null

            },
            {
                ProjectTitle: "Trading Simulator",
                Description1: "A web app for simulating stock trading in a risk-free environment. Practice strategies, track portfolio performance, and gain market experience — all without using real money. Built using .NET and C# on the backend, with a React and TypeScript frontend.",
                Description2: "The web app allows you so search for a stock using with its stock symbol, here you get some basic information and the options to view more information or buy the stock, where if buying you'll be asked to select the amount you want to purchase. This amount of stocks will then be added to your portfolio, where you're able to manage your stocks and watch them grow.",
                Description3: "Real API data is used to get the actual prices and information of stocks, which can be used to make an assessment of whether the stock should be bought or not. This full information can be seen on the Stock's page, and other APIs are even used to get information before making a decision such as an AI Assistant or recent news.",
                Description4: "On the portfolio page the user is able to view their current investment and how much it has grown. First entering the portfolio page they will be given the an overview of their portfolio, an deither scrolling down or clicking the button on the bottom left brings them to all of their stock records where they are able to search and sort, easily viewing their stocks and which ones have grown or fallen.",
                Description5: "Evem though the project isnt completely finished yet, I am taking my time and enjoying the process, adding things in a fun way such as an animated logo when hovering over it and such. While there are still many things to add I such as a currently popular stocks section on the Home page, it is able to complete its core functionalites flawlessly.",
                Img1: '/Projects/Images/TradeSim2.png',
                Img2: '/Projects/Images/TradeSim3.png',
                Img3: '/Projects/Images/TradeSim.png',
                Img4: '/Projects/Images/TradeSim4.png',
                TechUsed: ['React', 'TypeScript', 'C#', '.Net', 'HTML5', 'CSS3'],
                Link: 'https://github.com/AashiqDina/TradingSimulator',
                TryableLink: null
            },
            {
                ProjectTitle: "AI Cooking-Site",
                Description1: "A simple site making use of the Hugging Face AI API along with React and JavaScript taking in each ingredient the user has to create a prompt, asking the AI for the ideal recipe and getting back instructions on how to create the dish.",
                Description2: "The user is presented with a simple easy to navigate interface, this interface includes a logo I designed myself as I always do for all of my projects. This particular logo was designed in Photoshop but I use many tools to design logos, even sometimes designing it by hand and most recently I have been using Figma along with just HTML and CSS to design the logos.",
                Description3: "In the search bar the user adds each ingredient one at a time. Once the user has at least three ingredients inputed they will be given the opportunity to generate a recipe. The output of the AI has been asked to be created in HTML Markup to make it look cleaner in its final outputIn the search bar, users can add ingredients one at a time. Once at least three ingredients have been entered, they’ll have the option to generate a recipe. The AI is instructed to return the recipe in HTML markup to ensure the final output appears clean and well-formatted.",
                Description4: "Everything seen is designed to be simple, mimicing the simplicity of a chef hat only making the buttons stick out for accessibility purposes. This site was meant to be a simple test for using an API on the frontend, testing out how well it would work returning HTML Markup as a response while giving the user valid information.",
                Description5: "",
                Img1: '/Projects/Images/CookAi.png',
                Img2: '/Projects/Images/CookAi2.png',
                Img3: '/Projects/Images/CookAi3.png',
                Img4: '/Projects/Images/CookAi4.png',
                TechUsed: [''],
                Link: 'https://github.com/AashiqDina/CookingAiSite',
                TryableLink: null
            },
            {
                ProjectTitle: "Simple Image Classifier",
                Description1: "A Simple image classifer made with Python, PyTorch and trained with the CIFAR10 dataset, achieving a training accuracy of 86% and a test accuracy of 74%",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/ImageClassifier.png',
                Img2: '',
                Img3: '',
                Img4: '',
                TechUsed: [''],
                Link: 'https://github.com/AashiqDina/Neural_Networks_Project/blob/main/NeuralNetworksProject.ipynb',
                TryableLink: null
            },
            {
                ProjectTitle: "Wordle-Like Game",
                Description1: "A word-guessing game built with JavaScript and React, inspired by Wordle. Players must guess the correct word before all the PC components are visually destroyed. Each guess removing one PC component where each component is more important than the last.",
                Description2: "Each letter is made to be a button so its easily keyboard accesible and the container is styled with flex-wrap to ensure the letters move to fit the screen size of any device making it work perfectly on anything. While simple its able to complete its goal with a simple UI very well.",
                Description3: "Each game started will select a random word from a long array of words for the user to guess from. Once the user has selected a letter the letter's background colour will turn either red or green to indicate if the letter is part of the word or not. If the letter is part of the word it will also be placed into its correct slot above on the word display section.",
                Description4: "If the user has won confetti will begin to fall from the top of the screen, the displayed word's colour will change to green, the remaining letter buttons will be greyed out and the new game button will become available, allowing the user to start a new game with another randomly selected word.",
                Description5: "If the User loses the full word will be shown to the user in red, a message will pop up at the top letting the player know they lost, the letter buttons will be greyed out and the new game button will become available for the user to start a new game.",
                Img1: '/Projects/Images/WordleLike (1).png',
                Img2: '/Projects/Images/WordleLike (2).png',
                Img3: '/Projects/Images/WordleLike (3).png',
                Img4: '/Projects/Images/WordleLike (4).png',
                TechUsed: [''],
                Link: 'https://github.com/AashiqDina/ReactHangManLikeGame',
                TryableLink: null
            },
                        {
                ProjectTitle: "Education-based Social Media iOS Application",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
                        {
                ProjectTitle: "Simple Discord Bot",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
                        {
                ProjectTitle: "Simple Unity Game Project",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
            {
                ProjectTitle: "Object-Oriented Java Text Game",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
            {
                ProjectTitle: "Simple SQL Databases Project",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
            {
                ProjectTitle: "Meme Generator",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
            {
                ProjectTitle: "Pandas Data Cleaner Project",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
            {
                ProjectTitle: "Simple Pet Services Site",
                Description1: "",
                Description2: "",
                Description3: "",
                Description4: "",
                Description5: "",
                Img1: './Images/TradeSim2.png',
                Img2: './Images/TradeSim3.png',
                Img3: './Images/TradeSim1.png',
                Img4: './Images/TradeSim4.png',
                TechUsed: [''],
                Link: null,
                TryableLink: null
            },
        ]
    )
}